plugins:
  qa_tags:
    client: true
    type: list
    default: 'question'
  qa_enabled:
    client: true
    default: true
  qa_undo_vote_action_window:
    default: 10
  qa_comment_limit_per_post:
    default: 10
    min: 1
    client: true
