plugins:
  qa_enabled:
    client: true
    default: true
  qa_undo_vote_action_window:
    default: 10
  qa_comment_limit_per_post:
    default: 10
    min: 1
    client: true
  qa_comment_max_raw_length:
    client: true
    hidden: true
    default: 600
  qa_enable_likes_on_answers:
    client: true
    default: false
